r"""Shared immutable rule evidence and proof results."""

from __future__ import annotations

from dataclasses import dataclass, replace
from enum import Enum
from typing import Any, Callable, Iterable

from ...data_structures.type_ast.ast import ConfigurationType as _ConfigurationType
from ...data_structures.type_ast.render import format_type_source


class Verdict(str, Enum):
    r"""Three-valued verdicts shared by both type engines and proof backends.

    UNKNOWN records an unresolved proof, including a timeout; it is neither a
    refutation nor a successful typing result. FALSE records a definite failure.
    """

    TRUE = "true"
    FALSE = "false"
    UNKNOWN = "unknown"


    def __str__(self) -> str:
        r"""Display the lowercase verdict."""
        return self.value


    @classmethod
    def from_value(cls, value: Any) -> "Verdict":
        r"""Normalize Boolean and textual backend results to a Verdict."""
        if isinstance(value, Verdict):
            return value
        if value is True or str(value).lower() in {"true", "yes", "valid", "proved"}:
            return cls.TRUE
        if value is False or str(value).lower() in {"false", "no", "invalid", "disproved"}:
            return cls.FALSE
        return cls.UNKNOWN


    @classmethod
    def combine(cls, values: Iterable["Verdict"]) -> "Verdict":
        r"""Combine verdicts with FALSE before UNKNOWN before TRUE."""
        values = tuple(values)
        if any(value == cls.FALSE for value in values):
            return cls.FALSE
        if any(value == cls.UNKNOWN for value in values):
            return cls.UNKNOWN
        return cls.TRUE


# Obligations store evidence without invoking provers. Candidate and active identify isolated
# ODE attempts.
@dataclass(frozen=True, slots=True)
class ProofObligation:
    r"""An independently auditable logical goal generated by a typing rule.

    kind selects FOL or dL proving. formula retains the original premise, while
    proof_formula records the simplified input actually sent to the backend.
    candidate identifies an isolated ODE attempt; active marks evidence belonging
    to the selected derivation. location identifies the generating judgment.
    """

    rule: str
    description: str
    formula: Any
    kind: str = "fol"
    verdict: Verdict = Verdict.UNKNOWN
    detail: str = ""
    proof_formula: Any | None = None
    active: bool = True
    candidate: str = ""
    location: str = ""


    def decided(
        self,
        verdict: Verdict,
        detail: str = "",
        proof_formula: Any | None = None,
    ) -> "ProofObligation":
        r"""Return an immutable copy with the verdict and actual prover input."""

        return replace(
            self,
            verdict=verdict,
            detail=detail,
            proof_formula=(
                self.formula if proof_formula is None else proof_formula
            ),
        )


@dataclass(frozen=True, slots=True)
class DLCheckResult:
    r"""An external dL verdict with backend evidence."""

    verdict: Verdict
    detail: str = ""


@dataclass(frozen=True, slots=True)
class Diagnostic:
    r"""A diagnostic with error severity, rule, and location."""

    verdict: Verdict
    message: str
    rule: str = ""
    location: str = ""


@dataclass(frozen=True, slots=True)
class DerivationStep:
    r"""An immutable snapshot of a rule application or immediate formula decision."""

    number: int
    rule: str
    location: str
    subject: str
    gamma: tuple[tuple[str, str], ...] = ()
    parameters: tuple[tuple[str, str], ...] = ()
    parameter_constraint: str = ""
    theta: tuple[tuple[str, str], ...] = ()
    path_condition: str = ""
    symbolic_state: tuple[tuple[str, str], ...] = ()
    result: str = ""
    detail: str = ""


    def completed(self, result: str, detail: str = "") -> "DerivationStep":
        r"""Return an immutable copy with the rule result and details."""

        return replace(self, result=result, detail=detail)


@dataclass(frozen=True, slots=True)
class RuleDerivationReport:
    r"""Shared audit evidence for Table 2 derivation and proofs.

    constructed_type can hold a complete candidate even when verdict is UNKNOWN.
    Component results may be partial after a failed premise. Consumers must use
    passed to distinguish verified results from unresolved candidates.
    """

    verdict: Verdict
    constructed_type: _ConfigurationType | None
    constructed_component_types: tuple[_ConfigurationType | None, ...]
    obligations: tuple[ProofObligation, ...]
    diagnostics: tuple[Diagnostic, ...]
    steps: tuple[DerivationStep, ...] = ()


    @property
    def passed(self) -> bool:
        r"""Return true only when every structural check and obligation passed."""
        return self.verdict == Verdict.TRUE


    def summary(self) -> str:
        r"""Return compact statistics for reports and test failures."""
        proved = sum(
            item.active and item.verdict == Verdict.TRUE
            for item in self.obligations
        )
        disproved = sum(
            item.active and item.verdict == Verdict.FALSE
            for item in self.obligations
        )
        unknown = sum(
            item.active and item.verdict == Verdict.UNKNOWN
            for item in self.obligations
        )
        if self.constructed_type is None:
            type_summary = "(none)"
        elif self.verdict is Verdict.TRUE:
            type_summary = format_type_source(self.constructed_type)
        else:
            type_summary = format_type_source(self.constructed_type)
        trust_summary = (
            "trusted"
            if self.verdict is Verdict.TRUE
            else "untrusted"
            if self.constructed_type is not None
            else "unavailable"
        )
        return (
            f"{self.verdict.value}: type={type_summary}; trust={trust_summary}; "
            f"obligations(proved={proved}, false={disproved}, unknown={unknown}); "
            f"diagnostics={len(self.diagnostics)}; steps={len(self.steps)}"
        )


    @staticmethod
    def _paper_premise(obligation: ProofObligation) -> str:
        r"""Describe the paper premise or expression definedness side condition."""

        exact_shapes = {
            "T-sigma": "[T-sigma-param]  H => phi[sigma]",
            "T-Assert": "[T-Assert]  phi => B",
            "T-Assign-post": "[T-Assign]  phi => phi'{e/x}",
            "T-Out": "[T-Out]  phi => refinement{e/eta}",
            "T-ODE-safety": (
                "[T-unrhd/T-unrhd-prime]  "
                "(phi and t=0) => [ODE,t'=1]"
                "(t<=d => safety)"
            ),
            "T-ODE-domain": "[T-unrhd]  phi => [ODE]B",
            "T-ODE-boundary": (
                "[T-unrhd-prime]  (phi and t=0) => "
                "[ODE,t'=1]"
                "((t<d => B) and (t=d => not B))"
            ),
            "T-mu": "[T-mu]  phi => invariant",
            "T-X": "[T-X]  phi => invariant",
        }
        if obligation.rule in exact_shapes:
            return exact_shapes[obligation.rule]
        if obligation.rule in {"T-Assign", "T-If"}:
            return (
                f"[{obligation.rule}] Definedness side condition required by an "
                "expression typing judgment"
            )
        return f"[{obligation.rule}] Concrete formula premise generated by rule expansion"


    @staticmethod
    def _proof_backend(kind: str) -> str:
        r"""Describe the backend used for a state, FOL, or dL obligation."""

        return {
            "state": 'Initial state substitution + Z3 expression evaluation',
            "fol": 'Z3 validity check (unsatisfiability of the negated formula)',
            "dl": 'Configured dL backend (usually KeYmaera X)',
        }.get(kind, f"Unknown proof kind {kind!r}")


    @staticmethod
    def _append_formula_block(
        lines: list[str],
        label: str,
        value: Any,
    ) -> None:
        r"""Append a titled, consistently indented formula block."""

        rendered = str(value)
        formula_lines = rendered.splitlines() or [""]
        lines.append(f"     {label}:")
        lines.extend(f"       {line}" for line in formula_lines)


    def _append_formula_inventory(
        self,
        lines: list[str],
        *,
        title: str,
        kinds: frozenset[str],
        label: str,
        empty_message: str,
    ) -> dict[int, str]:
        r"""List prover inputs and map obligation indices to formula identifiers."""

        selected = tuple(
            (source_index, obligation)
            for source_index, obligation in enumerate(
                self.obligations,
                start=1,
            )
            if obligation.kind in kinds
        )
        lines.extend(("", title, f"Formula count : {len(selected)}"))
        if not selected:
            lines.append(empty_message)
            return {}

        status_labels = {
            Verdict.TRUE: 'proved',
            Verdict.FALSE: 'failed',
            Verdict.UNKNOWN: 'unproved',
        }
        references: dict[int, str] = {}
        displayed_formulas: dict[str, str] = {}
        for formula_index, (source_index, obligation) in enumerate(
            selected,
            start=1,
        ):
            formula_reference = f"{label}{formula_index:02d}"
            references[source_index] = formula_reference
            lines.extend(
                (
                    "",
                    f"[{formula_reference}] corresponds to O{source_index:02d} | "
                    f"{status_labels[obligation.verdict]} | "
                    f"{obligation.rule} | {obligation.kind.upper()}",
                    '     Candidate : '
                    + (obligation.candidate or 'deterministic rule')
                    + ('(used in final verdict)' if obligation.active else '(not selected)'),
                    f"     Formula role : {obligation.description}",
                    '     Judgment location : ' + (obligation.location or "-"),
                    f"     Proof backend : {self._proof_backend(obligation.kind)}",
                )
            )
            proof_formula = (
                obligation.formula
                if obligation.proof_formula is None
                else obligation.proof_formula
            )
            rendered_formula = str(proof_formula)
            previous_reference = displayed_formulas.get(rendered_formula)
            if previous_reference is None:
                self._append_formula_block(
                    lines,
                    'Checked formula',
                    proof_formula,
                )
                displayed_formulas[rendered_formula] = formula_reference
            else:
                lines.append(
                    (
                        '     Checked formula : same as ['
                        f'{previous_reference}'
                        ']; not repeated'
                    )
                )
            lines.append(f"     Verdict : {obligation.verdict.value}")
        return references


    def format_detailed(
        self,
        *,
        purpose: str = "construction",
        displayed_type: _ConfigurationType | None = None,
    ) -> str:
        r"""Display FOL/dL formulas, derivation traces, diagnostics, and trust status."""

        if purpose not in {"construction", "checking"}:
            raise ValueError("purpose must be 'construction' or 'checking'")
        is_checking = purpose == "checking"

        derivation_complete = self.constructed_type is not None
        type_trusted = self.verdict is Verdict.TRUE and derivation_complete
        if type_trusted:
            trust_status = 'trusted (all obligations verified)'
        elif not derivation_complete:
            trust_status = 'not applicable (no complete type)'
        elif self.verdict is Verdict.UNKNOWN:
            trust_status = 'untrusted (unverified obligations)'
        else:
            trust_status = 'untrusted (failed obligations)'
        if is_checking:
            verdict_explanations = {
                Verdict.TRUE: (
                    'The supplied Type matches all rule conclusions and all proof '
                    'obligations passed'
                ),
                Verdict.FALSE: (
                    'An environment error, Type mismatch, or unsatisfied proof obligation '
                    'was found'
                ),
                Verdict.UNKNOWN: (
                    (
                        'All Type structure was consumed by the rules, but a required '
                        'proof obligation remains unresolved'
                    )
                    if derivation_complete
                    else 'Type checking is incomplete with unresolved premises or diagnostics'
                ),
            }
            report_title = '=== Supplied Type checking and proof report ==='
            progress_label = 'Rule checking'
            result_label = 'Type matching'
            type_label = 'Supplied Type source'
            rendered_type = displayed_type
        else:
            verdict_explanations = {
                Verdict.TRUE: (
                    'All structural checks, static typing premises, and proof obligations '
                    'passed'
                ),
                Verdict.FALSE: (
                    'A structural/static typing error or unsatisfied proof obligation was '
                    'found'
                ),
                Verdict.UNKNOWN: (
                    (
                        'Rule derivation is complete, but a required proof obligation '
                        'remains unresolved; the constructed type is a complete, '
                        'unverified, untrusted candidate'
                    )
                    if derivation_complete
                    else (
                        'Rule derivation did not produce a unique complete type, with '
                        'unresolved premises or diagnostics'
                    )
                ),
            }
            report_title = '=== Type construction and proof report ==='
            progress_label = 'Rule derivation'
            result_label = 'Type construction'
            type_label = 'Constructed Type source'
            rendered_type = self.constructed_type
        lines = [
            report_title,
            f"Overall verdict : {self.verdict.value}",
            f"Verdict detail : {verdict_explanations[self.verdict]}",
            f"{progress_label} : " + ('complete' if derivation_complete else 'incomplete'),
            f"{result_label} : " + ('success' if derivation_complete else 'failed'),
            f"Type trust : {trust_status}",
            f"{type_label} : "
            + (
                format_type_source(rendered_type)
                if rendered_type is not None
                else "(none)"
            ),
        ]

        if len(self.constructed_component_types) > 1:
            if is_checking:
                component_heading = '=== Supplied configuration component types ==='
            elif type_trusted:
                component_heading = '=== Configuration component types ==='
            elif self.verdict is Verdict.UNKNOWN:
                component_heading = '=== Candidate configuration component types (unverified) ==='
            else:
                component_heading = (
                    '=== Candidate configuration component types (failed obligations) ==='
                )
            lines.extend(("", component_heading))
            for index, component_type in enumerate(
                self.constructed_component_types,
                start=1,
            ):
                rendered_component = (
                    format_type_source(component_type)
                    if component_type is not None
                    else "(failed)"
                )
                lines.append(f"K{index}: {rendered_component}")

        proved = sum(
            item.active and item.verdict == Verdict.TRUE
            for item in self.obligations
        )
        disproved = sum(
            item.active and item.verdict == Verdict.FALSE
            for item in self.obligations
        )
        unknown = sum(
            item.active and item.verdict == Verdict.UNKNOWN
            for item in self.obligations
        )

        # Expand prover inputs once by logic kind; ordered records reference their formula
        # identifiers.
        active_count = proved + disproved + unknown
        inactive_count = len(self.obligations) - active_count
        formula_references = self._append_formula_inventory(
            lines,
            title=(
                '=== First-order logic (FOL) proof formulas for type checking ==='
                if is_checking
                else '=== First-order logic (FOL) proof formulas for type construction ==='
            ),
            kinds=frozenset({"state", "fol"}),
            label="FOL",
            empty_message='(no first-order logic formulas)',
        )
        formula_references.update(self._append_formula_inventory(
            lines,
            title=(
                '=== Differential dynamic logic (dL) proof formulas for type checking ==='
                if is_checking
                else '=== Differential dynamic logic (dL) proof formulas for type construction ==='
            ),
            kinds=frozenset({"dl"}),
            label="DL",
            empty_message='(no dL formulas)',
        ))

        lines.extend(
            (
                "",
                '=== Sequential formula decisions ===',
                f"Proof records : {len(self.obligations)}",
                f"Active proof obligations : {active_count}",
                f"Inactive candidate obligations : {inactive_count}",
                f"Proved   : {proved}",
                f"Failed   : {disproved}",
                f"Unproved : {unknown}",
            )
        )
        if not self.obligations:
            lines.append('(no formula decisions)')
        status_labels = {
            Verdict.TRUE: 'proved',
            Verdict.FALSE: 'failed',
            Verdict.UNKNOWN: 'unproved',
        }
        retention_labels = {
            Verdict.TRUE: 'resolved; formula and proof evidence retained for audit',
            Verdict.FALSE: 'failed; proof obligation requires correction or review',
            Verdict.UNKNOWN: 'unresolved; a trusted proof backend or manual proof is required',
        }
        for index, obligation in enumerate(self.obligations, start=1):
            lines.extend(
                (
                    "",
                    f"[O{index:02d}] {status_labels[obligation.verdict]} | "
                    f"{obligation.rule} | {obligation.kind.upper()}",
                    '     Candidate : '
                    + (obligation.candidate or 'deterministic rule')
                    + ('(used in final verdict)' if obligation.active else '(not selected)'),
                    f"     Paper premise : {self._paper_premise(obligation)}",
                    f"     Proof goal : {obligation.description}",
                    '     Judgment location : ' + (obligation.location or "-"),
                    f"     Proof backend : {self._proof_backend(obligation.kind)}",
                )
            )
            proof_formula = (
                obligation.formula
                if obligation.proof_formula is None
                else obligation.proof_formula
            )
            formula_reference = formula_references.get(index)
            if str(obligation.formula) == str(proof_formula):
                if formula_reference is None:
                    self._append_formula_block(
                        lines,
                        'Rule formula / actual prover input',
                        obligation.formula,
                    )
                else:
                    lines.append(
                        (
                            '     Rule formula matches actual prover input : see ['
                            f'{formula_reference}'
                            ']'
                        )
                    )
            else:
                self._append_formula_block(
                    lines,
                    'Rule-generated formula (original)',
                    obligation.formula,
                )
                if formula_reference is None:
                    self._append_formula_block(
                        lines,
                        'Actual prover input',
                        proof_formula,
                    )
                else:
                    lines.append(
                        f"     Actual prover input : see [{formula_reference}]"
                    )
            lines.append(f"     Verdict : {obligation.verdict.value}")
            if obligation.detail:
                lines.append(f"     Prover detail: {obligation.detail}")
            lines.append(
                '     Resolution : '
                + retention_labels[obligation.verdict]
            )

        unresolved = tuple(
            (index, obligation)
            for index, obligation in enumerate(self.obligations, start=1)
            if obligation.active and obligation.verdict != Verdict.TRUE
        )
        lines.extend(("", '=== Unresolved or failed proof obligations ==='))
        if not unresolved:
            lines.append('(none; all generated proof obligations were proved)')
        for index, obligation in unresolved:
            next_action = (
                'Revise the program/annotations or inspect the counterexample'
                if obligation.verdict == Verdict.FALSE
                else (
                    'Configure a trusted proof backend, extend the proof strategy, or '
                    'prove manually'
                )
            )
            lines.append(
                f"[O{index:02d}] {status_labels[obligation.verdict]} | "
                f"{obligation.rule} | Next action: {next_action}"
            )

        lines.extend(("", '=== Rule execution trace ==='))
        if not self.steps:
            lines.append('(no rule steps recorded)')
        for step in sorted(self.steps, key=lambda item: item.number):
            location = step.location or "-"
            lines.append(f"[{step.number:02d}] {step.rule} @ {location}")
            lines.append(f"     Checked object : {step.subject}")
            if step.gamma:
                lines.append(
                    "     Gamma    : "
                    + ", ".join(f"{name}:{value_type}" for name, value_type in step.gamma)
                )
            else:
                lines.append("     Gamma    : {}")
            if step.parameters:
                lines.append(
                    "     Parameters: "
                    + ", ".join(
                        f"{name}:{value_type}"
                        for name, value_type in step.parameters
                    )
                )
                lines.append(
                    '     Parameter constraint : '
                    + (step.parameter_constraint or "True")
                )
            if step.theta:
                lines.append(
                    "     Theta    : "
                    + ", ".join(f"{name}:{channel_type}" for name, channel_type in step.theta)
                )
            if step.path_condition:
                lines.append(f"     Path condition : {step.path_condition}")
            if step.symbolic_state:
                lines.append(
                    '     Symbolic state : '
                    + ", ".join(f"{name}={term}" for name, term in step.symbolic_state)
                )
            if step.result:
                result_lines = step.result.splitlines()
                lines.append(f"     Rule result : {result_lines[0]}")
                lines.extend(
                    f"                  {line}"
                    for line in result_lines[1:]
                )
            if step.detail:
                lines.append(f"     Detail     : {step.detail}")

        lines.extend(("", '=== Diagnostics ==='))
        if not self.diagnostics:
            lines.append('(no diagnostics; no structural or typing errors found)')
        for index, diagnostic in enumerate(self.diagnostics, start=1):
            lines.append(
                f"[{index:02d}] {diagnostic.verdict.value} "
                f"{diagnostic.rule or '-'} @ {diagnostic.location or '-'}"
            )
            lines.append(f"     {diagnostic.message}")

        lines.extend(
            (
                "",
                '=== Summary ===',
                f"Rule steps : {len(self.steps)}",
                f"Proof records : {len(self.obligations)}",
                f"Proof obligations : {active_count} "
                f"(true={proved}, false={disproved}, unknown={unknown})",
                f"Inactive candidate obligations : {inactive_count}",
                f"Outstanding obligations : {len(unresolved)} "
                f"(failed={disproved}, unproved={unknown})",
                f"Diagnostic count : {len(self.diagnostics)}",
            )
        )
        return "\n".join(lines)


DLChecker = Callable[
    [ProofObligation],
    DLCheckResult | Verdict | bool | str | None,
]

__all__ = [
    "DLCheckResult",
    "DLChecker",
    "DerivationStep",
    "Diagnostic",
    "ProofObligation",
    "RuleDerivationReport",
    "Verdict",
]
